on: push
name: Publish Website over SFTP
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 1.studio.boardgamearena.com
        username: theod
        password: ${{ secrets.SSH_AUTHENTIFICATION_PASSWORD }}
        port: 2022
        protocol: sftp
        local-dir: ./tutotheod/

