on: push
name: Synchronize BGA server
jobs:
  sync_job:
    name: SFTP-SSH-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SFTP-SSH-Action
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: '1.studio.boardgamearena.com'
        username: 'theod'
        port: '2022'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{ secrets.SSH_AUTHENTIFICATION_PASSWORD }}
        local_path: '.'
        remote_path: './tutotheod/'
