on: push
name: Synchronize BGA server
jobs:
  SFTP-Sync-Action:
    name: SFTP-Sync-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SFTP-Sync-Action
      uses: Creepios/sftp-action@v1.0.5
      with:
        host: 1.studio.boardgamearena.com
        port: 2022
        username: theod
        localPath: ./
        remotePath: ./tutotheod/
        privateKey: ${{ secrets.SSH_AUTHENTIFICATION_PASSWORD }}

