on: push
name: Synchronize BGA server
jobs:
  sync_job:
    name: SFTP-SSH-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SFTP-SSH-Action
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: "1.studio.boardgamearena.com"
        remote-port: "2022"
        remote-user: "theod"
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote-password: ${{ secrets.SSH_AUTHENTIFICATION_PASSWORD }}
        remote-path: "./tutotheod/"
