on: push
name: Synchronize BGA server
jobs:
  sync_job:
    name: SFTP-SSH-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SFTP-SSH-Action
      uses: wangyucode/sftp-upload-action@v2.0.3
      with:
        host: '1.studio.boardgamearena.com'
        port: 2022
        username: 'theod'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_AUTHENTIFICATION_PASSWORD }}
        localDir: '.'
        remoteDir: '/tutotheod'
        exclude: '.gitignore'
